/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.person;
import model.personDirectory;

/**
 *
 * @author Lenevo
 */
public class ViewListJPanel extends javax.swing.JPanel {
     private JPanel UserProcessContainer;
     private personDirectory personDirectory;
     private person person;
    
     
     
    /**
     * Creates new form ViewListJPanel
     * @param person
     */    
     public ViewListJPanel(JPanel UserProcessContainer, personDirectory ListPerson, person person) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
        this.person = person;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHomeState = new javax.swing.JTextField();
        lblHomePhoneNumber = new javax.swing.JLabel();
        txtHomePhoneNumber = new javax.swing.JTextField();
        lblWorkAddress = new javax.swing.JLabel();
        lblWorkStreetName = new javax.swing.JLabel();
        txtWorkStreetAddress = new javax.swing.JTextField();
        lblWorkCity = new javax.swing.JLabel();
        txtWorkCity = new javax.swing.JTextField();
        lblWorkZipCode = new javax.swing.JLabel();
        txtWorkZipCode = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblWorkUnitNumber = new javax.swing.JLabel();
        txtWorkUnitNumber = new javax.swing.JTextField();
        lblHomeAdd = new javax.swing.JLabel();
        lblWorkState = new javax.swing.JLabel();
        lblHomeStreetName = new javax.swing.JLabel();
        txtWorkState = new javax.swing.JTextField();
        txtHomeStreetAddress = new javax.swing.JTextField();
        lblWorkPhoneNumber = new javax.swing.JLabel();
        lblHomeCity = new javax.swing.JLabel();
        txtWorkPhoneNumber = new javax.swing.JTextField();
        txtHomeCity = new javax.swing.JTextField();
        lblHomeZipCode = new javax.swing.JLabel();
        txtHomeZipCode = new javax.swing.JTextField();
        lblHomeUnitNumber = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtHomeUnitNumber = new javax.swing.JTextField();
        lblHomeState = new javax.swing.JLabel();
        lblPersonProfile = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdateDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));

        lblHomePhoneNumber.setText("Phone Number :");

        lblWorkAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblWorkAddress.setText("Work Address");

        lblWorkStreetName.setText("Street Name:");

        lblWorkCity.setText("City:");

        lblWorkZipCode.setText("Zip Code :");

        lblWorkUnitNumber.setText("Unit Number :");

        lblHomeAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblHomeAdd.setText("Home Address");

        lblWorkState.setText("State:");

        lblHomeStreetName.setText("Street Name : ");

        lblWorkPhoneNumber.setText("Phone Number:");

        lblHomeCity.setText("City :");

        txtHomeCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeCityActionPerformed(evt);
            }
        });

        lblHomeZipCode.setText("Zip Code :");

        txtHomeZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeZipCodeActionPerformed(evt);
            }
        });

        lblHomeUnitNumber.setText("Unit Number :");

        lblFirstName.setText("First Name: ");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name:");

        lblSsn.setText("Social Security Number:");

        lblAge.setText("Age:");

        lblHomeState.setText("State :");

        lblPersonProfile.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblPersonProfile.setText("Person Profile");

        btnBack.setText(">>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdateDetails.setText("Update Details");
        btnUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addGap(249, 249, 249)
                .addComponent(lblPersonProfile)
                .addContainerGap(383, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateDetails)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHomePhoneNumber)
                            .addGap(18, 18, 18)
                            .addComponent(txtHomePhoneNumber))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFirstName)
                                .addComponent(lblLastName))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtLastName)))
                        .addComponent(lblHomeAdd)
                        .addComponent(lblHomeUnitNumber)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHomeCity)
                                .addComponent(lblHomeZipCode)
                                .addComponent(lblHomeState)
                                .addComponent(lblHomeStreetName))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHomeStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHomeCity, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(txtHomeUnitNumber)
                                    .addComponent(txtHomeState)))))
                    .addGap(157, 157, 157)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSsn)
                        .addComponent(lblWorkAddress)
                        .addComponent(lblAge)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblWorkCity)
                                .addComponent(lblWorkPhoneNumber)
                                .addComponent(lblWorkStreetName)
                                .addComponent(lblWorkZipCode)
                                .addComponent(lblWorkUnitNumber)
                                .addComponent(lblWorkState))
                            .addGap(102, 102, 102)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWorkUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtWorkStreetAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtWorkCity)
                                    .addComponent(txtWorkZipCode)
                                    .addComponent(txtWorkPhoneNumber)))))
                    .addContainerGap(66, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblPersonProfile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)))
                .addGap(63, 63, 63)
                .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdateDetails))
                .addGap(56, 56, 56))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSsn))
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLastName)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAge))
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblWorkAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblHomeAdd))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHomeStreetName)
                                .addComponent(txtHomeStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtWorkStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWorkStreetName))))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblWorkCity)
                                .addComponent(txtWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHomeCity)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHomeZipCode)
                                .addComponent(txtWorkZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWorkZipCode))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHomeUnitNumber)
                                .addComponent(txtHomeUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblWorkUnitNumber)
                                .addComponent(txtWorkUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblWorkState)
                                .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHomeState)
                                .addComponent(txtHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHomePhoneNumber)
                        .addComponent(txtHomePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblWorkPhoneNumber)
                        .addComponent(txtWorkPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(125, 125, 125)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHomeCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeCityActionPerformed

    private void txtHomeZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeZipCodeActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
     UserProcessContainer.remove(this);
        Component[] panelStack=UserProcessContainer.getComponents();
        JPanel lastPanel=(JPanel) panelStack[panelStack.length - 1];
        ListPersonJPanel listpersonJPanel=(ListPersonJPanel) lastPanel;
        listpersonJPanel.populateTable();
        
        CardLayout layout=(CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String FirstName = txtFirstName.getText();
        String LastName = txtLastName.getText();
        String SSN = txtSsn.getText();
        String Age = txtAge.getText();
        String WorkStreet = txtWorkStreetAddress.getText();
        String WorkCity = txtWorkCity.getText();
        String WorkState = txtWorkState.getText();
        String WorkUnitNumber = txtWorkUnitNumber.getText();
        String WorkZIP = txtWorkZipCode.getText();
        String HomeStreet = txtHomeStreetAddress.getText();
        String HomeCity = txtHomeCity.getText();
        String HomeState = txtHomeState.getText();
        String HomeUnitNumber = txtHomeUnitNumber.getText();
        String HomeZIP = txtHomeZipCode.getText();
        String HomePhoneNumber = txtHomePhoneNumber.getText();
        String WorkPhoneNumber = txtWorkPhoneNumber.getText();
        
        if (FirstName.isBlank() || LastName.isBlank() || SSN.isBlank() || Age.isBlank() || WorkStreet.isBlank() || WorkCity.isBlank() || WorkState.isBlank() || WorkUnitNumber.isBlank()||WorkPhoneNumber.isBlank()||WorkZIP.isBlank() || HomeStreet.isBlank() || HomeCity.isBlank() || HomeState.isBlank() || HomeUnitNumber.isBlank()||HomePhoneNumber.isBlank()||HomeZIP.isBlank()){
            JOptionPane.showMessageDialog(null,"All fields are mandatory");
            return;
        }
        person.setFirstName(FirstName);
        person.setLastName(LastName);
        person.setSSN(Long.parseLong(SSN));
        person.setAge(Integer.parseInt(Age));
        person.getHomeAddress().setStreet(HomeStreet);
        person.getHomeAddress().setCity(HomeCity);
        person.getHomeAddress().setState(HomeState);
        person.getHomeAddress().setZIP(HomeZIP);
        person.getHomeAddress().setUnitNumber(HomeUnitNumber);
        person.getWorkAddress().setCity(WorkCity);
        person.getWorkAddress().setState(WorkState);
        person.getWorkAddress().setStreet(WorkStreet);
        person.getWorkAddress().setUnitNumber(WorkUnitNumber);
        person.getWorkAddress().setZIP(WorkZIP);
        person.getWorkAddress().setPhoneNumber(WorkPhoneNumber);
        person.getHomeAddress().setPhoneNumber(HomePhoneNumber);
        
        JOptionPane.showMessageDialog(null,"Profile successfully updated","Warning",JOptionPane.WARNING_MESSAGE);
        setViewMode();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDetailsActionPerformed
       setEditMode();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdateDetails;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAdd;
    private javax.swing.JLabel lblHomeCity;
    private javax.swing.JLabel lblHomePhoneNumber;
    private javax.swing.JLabel lblHomeState;
    private javax.swing.JLabel lblHomeStreetName;
    private javax.swing.JLabel lblHomeUnitNumber;
    private javax.swing.JLabel lblHomeZipCode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPersonProfile;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblWorkCity;
    private javax.swing.JLabel lblWorkPhoneNumber;
    private javax.swing.JLabel lblWorkState;
    private javax.swing.JLabel lblWorkStreetName;
    private javax.swing.JLabel lblWorkUnitNumber;
    private javax.swing.JLabel lblWorkZipCode;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomePhoneNumber;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeStreetAddress;
    private javax.swing.JTextField txtHomeUnitNumber;
    private javax.swing.JTextField txtHomeZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtWorkCity;
    private javax.swing.JTextField txtWorkPhoneNumber;
    private javax.swing.JTextField txtWorkState;
    private javax.swing.JTextField txtWorkStreetAddress;
    private javax.swing.JTextField txtWorkUnitNumber;
    private javax.swing.JTextField txtWorkZipCode;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
       txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtSsn.setText(String.valueOf(person.getSSN()));
        txtAge.setText(String.valueOf(person.getAge()));
        txtHomeStreetAddress.setText(person.getHomeAddress().getStreet());
        txtHomeUnitNumber.setText(String.valueOf(person.getHomeAddress().getUnitNumber()));
        txtHomeCity.setText(person.getHomeAddress().getCity());
        txtHomeState.setText(person.getHomeAddress().getState());
        txtHomeZipCode.setText(String.valueOf(person.getHomeAddress().getZIP()));
        txtHomePhoneNumber.setText(String.valueOf(person.getHomeAddress().getPhoneNumber()));
        txtWorkStreetAddress.setText(person.getWorkAddress().getStreet());
        txtWorkUnitNumber.setText(String.valueOf(person.getWorkAddress().getUnitNumber()));
        txtWorkCity.setText(person.getWorkAddress().getCity());
        txtWorkState.setText(person.getWorkAddress().getState());
        txtWorkZipCode.setText(String.valueOf(person.getWorkAddress().getZIP()));
        txtWorkPhoneNumber.setText(String.valueOf(person.getWorkAddress().getPhoneNumber()));


        btnSave.setEnabled(false);
        btnUpdateDetails.setEnabled(true);

    }
     private void setViewMode() {
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtSsn.setEnabled(false);
        txtAge.setEnabled(false);
        txtHomeStreetAddress.setEnabled(false);
        txtHomeUnitNumber.setEnabled(false);
        txtHomeCity.setEnabled(false);
        txtHomeState.setEnabled(false);
        txtHomeZipCode.setEnabled(false);
        txtHomePhoneNumber.setEnabled(false);
        txtWorkStreetAddress.setEnabled(false);
        txtWorkUnitNumber.setEnabled(false);
        txtWorkCity.setEnabled(false);
        txtWorkState.setEnabled(false);
        txtWorkZipCode.setEnabled(false);
        txtWorkPhoneNumber.setEnabled(false);
        
        
        btnSave.setEnabled(false);
        btnUpdateDetails.setEnabled(true);
    }
       
    private void setEditMode() {
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSsn.setEnabled(true);
        txtAge.setEnabled(true);
        txtHomeStreetAddress.setEnabled(true);
        txtHomeUnitNumber.setEnabled(true);
        txtHomeCity.setEnabled(true);
        txtHomeState.setEnabled(true);
        txtHomeZipCode.setEnabled(true);
        txtHomePhoneNumber.setEnabled(true);
        txtWorkStreetAddress.setEnabled(true);
        txtWorkUnitNumber.setEnabled(true);
        txtWorkCity.setEnabled(true);
        txtWorkState.setEnabled(true);
        txtWorkZipCode.setEnabled(true);
        txtWorkPhoneNumber.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdateDetails.setEnabled(false);
       }  
}
