/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Create extends javax.swing.JPanel {
    Product product;

    /**
     * Creates new form Create
     */
    public Create( Product p) {
        product = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverslicenselbl = new javax.swing.JLabel();
        ziplbl = new javax.swing.JLabel();
        occupationlbl = new javax.swing.JLabel();
        telephonelbl = new javax.swing.JLabel();
        organizationlbl = new javax.swing.JLabel();
        faxnolbl = new javax.swing.JLabel();
        fnamelbl = new javax.swing.JLabel();
        ssnlbl = new javax.swing.JLabel();
        lnamelbl = new javax.swing.JLabel();
        genderlbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        addressline1lbl = new javax.swing.JLabel();
        addressline2lbl = new javax.swing.JLabel();
        phonelbl = new javax.swing.JLabel();
        citylbl = new javax.swing.JLabel();
        driverslicensestatelbl = new javax.swing.JLabel();
        statelbl = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        socialmedialinklbl = new javax.swing.JLabel();
        emergencontactlbl = new javax.swing.JLabel();
        fnametextfield = new javax.swing.JTextField();
        gendertextfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        ssntextfield = new javax.swing.JTextField();
        phonetextfield = new javax.swing.JTextField();
        driverlicensestatetextfield = new javax.swing.JTextField();
        driverslicensenotextfield = new javax.swing.JTextField();
        occupationtextfield = new javax.swing.JTextField();
        organizationtextfield = new javax.swing.JTextField();
        socialmedialinktextfield = new javax.swing.JTextField();
        addressline1textfield = new javax.swing.JTextField();
        addressline2textfield = new javax.swing.JTextField();
        citytextfield = new javax.swing.JTextField();
        emergencycontacttextfield = new javax.swing.JTextField();
        statetextfield = new javax.swing.JTextField();
        faxnotextfield = new javax.swing.JTextField();
        ziptextfield = new javax.swing.JTextField();
        lnametextfield = new javax.swing.JTextField();
        telephonetextfield = new javax.swing.JTextField();
        educationlbl = new javax.swing.JLabel();
        educationtextfield = new javax.swing.JTextField();

        driverslicenselbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        driverslicenselbl.setText("Driver License No");

        ziplbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ziplbl.setText("ZIP");

        occupationlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        occupationlbl.setText("Occupation");

        telephonelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telephonelbl.setText("Telephone No");

        organizationlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        organizationlbl.setText("Organization");

        faxnolbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        faxnolbl.setText("Fax No");

        fnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fnamelbl.setText("First Name");

        ssnlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ssnlbl.setText("SSN");

        lnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lnamelbl.setText("Last Name");

        genderlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genderlbl.setText("Gender");

        emaillbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emaillbl.setText("Email");

        addressline1lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressline1lbl.setText("Address Line 1");

        addressline2lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressline2lbl.setText("Address Line 2");

        phonelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        phonelbl.setText("Phone");

        citylbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        citylbl.setText("City");

        driverslicensestatelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        driverslicensestatelbl.setText("Drivers License State");

        statelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statelbl.setText("State");

        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        socialmedialinklbl.setText("Social media link");

        emergencontactlbl.setText("Emergency Contact");

        lnametextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametextfieldActionPerformed(evt);
            }
        });

        educationlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        educationlbl.setText("Education");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addressline1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(socialmedialinklbl)
                        .addComponent(organizationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(occupationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(driverslicenselbl)
                        .addComponent(driverslicensestatelbl)
                        .addComponent(phonelbl)
                        .addComponent(emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressline2lbl)
                        .addComponent(citylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ziplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lnamelbl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(citytextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(addressline2textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(gendertextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(emailtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(phonetextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(driverlicensestatetextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(driverslicensenotextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(occupationtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(organizationtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(socialmedialinktextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(ssntextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(addressline1textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(fnametextfield)
                    .addComponent(statetextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(ziptextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(lnametextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(savebtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faxnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emergencontactlbl)
                            .addComponent(telephonelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emergencycontacttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationtextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(faxnotextfield)
                                .addComponent(telephonetextfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnamelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lnamelbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationlbl)
                            .addComponent(educationtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderlbl)
                            .addComponent(gendertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emaillbl)
                            .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faxnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephonetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephonelbl))
                        .addGap(18, 18, 18)
                        .addComponent(faxnotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phonelbl)
                            .addComponent(phonetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emergencycontacttextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emergencontactlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driverslicensestatelbl)
                            .addComponent(driverlicensestatetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driverslicenselbl)
                            .addComponent(driverslicensenotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(occupationlbl)
                            .addComponent(occupationtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organizationlbl)
                            .addComponent(organizationtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(socialmedialinklbl)
                            .addComponent(socialmedialinktextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssnlbl)
                            .addComponent(ssntextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressline1lbl)
                            .addComponent(addressline1textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressline2textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressline2lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citylbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ziplbl)
                            .addComponent(ziptextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(savebtn)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        
        String d_FirstName = fnametextfield.getText();
        String d_LastName= lnametextfield.getText();
        String Gender = gendertextfield.getText();
        String Email = emailtextfield.getText();
        String Phone = phonetextfield.getText();
        String d_DriversLicenseNo =driverslicensenotextfield.getText();
        String d_DriversLicenseState = driverlicensestatetextfield.getText() ;
        String Occupation = occupationtextfield.getText();
        String Organization = organizationtextfield.getText();
        String Education = educationtextfield.getText();
        String SocialMediaLink = socialmedialinktextfield.getText();
        String SSN = ssntextfield.getText();
        String d_AddressLine1 = addressline1textfield.getText();
        String d_AddressLine2 = addressline2textfield.getText();
        String City = citytextfield.getText();
        String State = statetextfield.getText();
        String ZIP = ziptextfield.getText(); 
        String d_TelephoneNumber = telephonetextfield.getText();
        String d_FaxNumber = faxnotextfield.getText();
        String d_EmergencyContact = emergencycontacttextfield.getText();
        
        product.setCity(City);
        product.setD_AddressLine1(d_AddressLine1);
        product.setD_AddressLine2(d_AddressLine2);
        product.setD_DriversLicenseNo(d_DriversLicenseNo);
        product.setD_DriversLicenseState(d_DriversLicenseState);
        product.setD_EmergencyContact(d_EmergencyContact);
        product.setD_FaxNumber(d_FaxNumber);
        product.setD_FirstName(d_FirstName);
        product.setD_LastName(d_LastName);
        product.setD_TelephoneNumber(d_TelephoneNumber);
        product.setEducation(Education);
        product.setEmail(Email);
        product.setGender(Gender);
        product.setOccupation(Occupation);
        product.setOrganization(Organization);
        product.setPhone(Phone);
        product.setSSN(SSN);
        product.setSocialMediaLink(SocialMediaLink);
        product.setState(State);
        product.setZIP(ZIP);
        
        JOptionPane.showMessageDialog(this,"Information Saved" , "Success", JOptionPane.PLAIN_MESSAGE);
        
        fnametextfield.setText("");
        lnametextfield.setText("");
        gendertextfield.setText("");
        emailtextfield.setText("");
        phonetextfield.setText("");
        driverslicensenotextfield.setText("");
        driverlicensestatetextfield.setText("") ;
        occupationtextfield.setText("");
        organizationtextfield.setText("");
        educationtextfield.setText("");
        socialmedialinktextfield.setText("");
        ssntextfield.setText("");
        addressline1textfield.setText("");
        addressline2textfield.setText("");
        citytextfield.setText("");
        statetextfield.setText("");
        ziptextfield.setText(""); 
        telephonetextfield.setText("");
        faxnotextfield.setText("");
        emergencycontacttextfield.setText("");
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void lnametextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametextfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressline1lbl;
    private javax.swing.JTextField addressline1textfield;
    private javax.swing.JLabel addressline2lbl;
    private javax.swing.JTextField addressline2textfield;
    private javax.swing.JLabel citylbl;
    private javax.swing.JTextField citytextfield;
    private javax.swing.JTextField driverlicensestatetextfield;
    private javax.swing.JLabel driverslicenselbl;
    private javax.swing.JTextField driverslicensenotextfield;
    private javax.swing.JLabel driverslicensestatelbl;
    private javax.swing.JLabel educationlbl;
    private javax.swing.JTextField educationtextfield;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JLabel emergencontactlbl;
    private javax.swing.JTextField emergencycontacttextfield;
    private javax.swing.JLabel faxnolbl;
    private javax.swing.JTextField faxnotextfield;
    private javax.swing.JLabel fnamelbl;
    private javax.swing.JTextField fnametextfield;
    private javax.swing.JLabel genderlbl;
    private javax.swing.JTextField gendertextfield;
    private javax.swing.JLabel lnamelbl;
    private javax.swing.JTextField lnametextfield;
    private javax.swing.JLabel occupationlbl;
    private javax.swing.JTextField occupationtextfield;
    private javax.swing.JLabel organizationlbl;
    private javax.swing.JTextField organizationtextfield;
    private javax.swing.JLabel phonelbl;
    private javax.swing.JTextField phonetextfield;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel socialmedialinklbl;
    private javax.swing.JTextField socialmedialinktextfield;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JTextField ssntextfield;
    private javax.swing.JLabel statelbl;
    private javax.swing.JTextField statetextfield;
    private javax.swing.JLabel telephonelbl;
    private javax.swing.JTextField telephonetextfield;
    private javax.swing.JLabel ziplbl;
    private javax.swing.JTextField ziptextfield;
    // End of variables declaration//GEN-END:variables






}
